 language: ruby
 # only install ci and assets gems:
 bundler_args: --without production:development:test
 rvm:
   - 1.9.3
   - 2.1.5
 matrix:
   fast_finish: true
 addons:
   apt:
     packages:
       - graphicsmagick
       - libreoffice-writer
       - inkscape
 before_install:
   - bundle --version
   - libreoffice --version
 notifications:
   email: false
